splash = {}
splash['NAO'] = {}
splash['NAO']['title'] = 'HURRELL NORTH ATLANTIC OSCILLATION (NAO) INDEX (STATION-BASED)'
splash['NAO']['description'] = 'The winter (December thru March) station-based index of the NAO is based on the difference of normalized sea level pressure (SLP) between Lisbon, Portugal and Stykkisholmur/Reykjavik, Iceland since 1864. Positive values of the NAO index are typically associated with stronger-than-average westerlies over the middle latitudes, more intense weather systems over the North Atlantic and wetter/milder weather over western Europe'
splash['NAO']['credits'] = 'Hurrell, James & National Center for Atmospheric Research Staff (Eds). Last modified 02 Dec 2013. The Climate Data Guide: Hurrell North Atlantic Oscillation (NAO) Index (station-based).'
splash['NAO']['home'] = ['https://climatedataguide.ucar.edu/climate-data/hurrell-north-atlantic-oscillation-nao-index-station-based','NCAR UCAR | Climate Data Guide']
splash['NAO']['sourcedata'] = ['https://climatedataguide.ucar.edu/sites/default/files/climate_index_files/nao_station_djfm.txt','Hurrell, James & National Center for Atmospheric Research Staff (Eds). Last modified 02 Dec 2013.']
splash['NAO']['nbviewer'] = ''
splash['NAO']['repository'] = ''
splash['NAO']['download'] = ''

splash['AMO'] = {}
splash['AMO']['title'] = 'ATLANTIC MULTIDECADAL OSCILLATION (AMO) INDEX'
splash['AMO']['description'] = 'The Atlantic Multidecadal Oscillation (AMO) is a mode of variability occurring in the North Atlantic Ocean and which has its principal expression in the sea surface temperature (SST) field.'
splash['AMO']['credits'] = '-------------'
splash['AMO']['home'] = ['http://www.esrl.noaa.gov/psd/','NOAA Earth System Research Laboratory - The Physical Sciences Division']
splash['AMO']['sourcedata'] = ['http://www.esrl.noaa.gov/psd/data/correlation/amon.us.long.data','amon.us.long.data']
splash['AMO']['nbviewer'] = ''
splash['AMO']['repository'] = ''
splash['AMO']['download'] = ''